blog/urls.py
from django.conf.urls import url
from . import views, views_cbv

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<id>\d+)/$', views.post_detail, name='post_detail'),

    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<id>\d+)/edit/$', views.post_edit, name='post_edit'),

    url(r'^cbv/$', views_cbv.post_list, name='cbv_post_list'),
    url(r'^cbv/(?P<id>\d+)/$', views_cbv.post_detail, name='cbv_post_detail'),

    url(r'^cbv/new/$', views_cbv.post_new, name='cbv_post_new'),
    url(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit, name='cbv_post_edit'),
    url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete, name='cbv_post_delete'),

    url(r'^comments/$', views.comment_list, name='comment_list'),
    url(r'^tests/$', views.test_list, name='test_list'),
]

start_django/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    url(r'^$', lambda r: redirect('blog:post_list'), name='root'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

blog/models.py
import re
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models
from django.forms import ValidationError


def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.\d+),([+-]?\d+\.\d+)$', value):
        raise ValidationError('Invalid LngLat Type')
    

class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdrawn'),
    )
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=100, verbose_name="Subject", help_text="input title, max 100")
    content = models.TextField(verbose_name="Content")
    photo = models.ImageField(blank=True, upload_to='blog/post/%Y/%m/%d')
    tag = models.CharField(max_length=50, blank=True, help_text="write tags")
    lnglat = models.CharField(max_length=30,
        validators=[lnglat_validator],
        help_text="\"longtitude,latitude\" type",
        blank=True
    )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    tag_set = models.ManyToManyField('Tag', blank=True)
    ip = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.title


    class Meta:
        ordering = ['-id']

    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args = [self.id])    


class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    tag = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.tag

blog/forms.py
from django import forms
from .models import Comment, Post
from start_django.widgets.naver_map_point_widget import NaverMapPointWidget


class PostForm(forms.ModelForm):
    # dummy = forms.CharField(widget=NaverMapPointWidget(attrs={'width': "100%", 'height': 500}))

    class Meta:
        model = Post
        fields = ['status', 'title', 'content', 'photo', 'lnglat', 'tag_set']
        widgets = {
            'lnglat': NaverMapPointWidget(attrs={'width': 600, 'height': 400}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'message']

blog/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from .forms import CommentForm, PostForm
from .models import Post, Comment


def post_list(request):
    qs = Post.objects.all().select_related('user')

    q = request.GET.get('q', '')
    if q:
        qs = Post.objects.filter(title__icontains=q)

    return render(request, 'blog/post_list.html', {
        'post_list': qs,
        'q': q,
    })



def post_detail(request, id):
    # try:
    #     post = Post.objects.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404

    post = get_object_or_404(Post, id=id)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post_id = id
            comment.save()
            messages.success(request, 'Successfully replied to post..')
            return redirect(post)
    else:
        form = CommentForm()        

    return render(request, 'blog/post_detail.html', {
        'post': post,
        'form': form,
    })


def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.ip = request.META['REMOTE_ADDR']
            post.save()
            messages.success(request, 'New post created successfully')
            return redirect(post)
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form': form,
    })


def post_edit(request, id):
    post = get_object_or_404(Post, id=id)

    if request.method=='POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.ip = request.META['REMOTE_ADDR']
            post.save()
            messages.success(request, 'Modfied Post')
            return redirect(post)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_new.html', {
        'form': form,
    })


def comment_list(request):
    qs = Comment.objects.all().select_related('post')
    return render(request, 'blog/comment_list.html', {
        'comment_list': qs,
    })


def test_list(request):
    qs = Post.objects.all().prefetch_related('comment_set')
    return render(request, 'blog/test_list.html', {
        'post_list': qs,
    })

blog/templates/blog/comment_list.html
{% extends 'blog/layout.html' %}

{% block content %}

<ul>
    {% for comment in comment_list %}
        <li>
        <strong> COMMENT : </strong>{{ comment.message }}
        <strong> POST : </strong>{{ comment.post.title }}
        </li>
        
    {% endfor %}
</ul>

{% endblock %}

blog/templates/blog/layout.html
{% extends "layout.html" %}

{% block title %}Start Django's Blog {% endblock %}

blog/templates/blog/post_confirm_delete.html
<h1>Delete ? {{post.title}}</h1>

<form action="" method="post">
    {% csrf_token %}
    <a href="{{ post.get_absolute_url }}"> No-wooo</a>
    <input type="submit" value="Delete" class="btn btn-warning">
</form>

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% load imagekit %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2>{{ post.title }}</h2>

            {% if post.photo %}
                <img src="{{ post.photo.url }}" alt="" style="max-width: 100%">

                {% thumbnail "300x300" post.photo %}
                
                {% thumbnail "300x300" post.photo as thumb %}
                <img src="{{thumb.url}}" width="{{thumb.width}}" height="{{thumb.heigth}}">

                {% thumbnail "300x300" post.photo -- alt="testimg" %}
            {% endif %}
            
                {{ post.content|linebreaks }}
            
            <hr/>
            
            <a href="{% url 'blog:cbv_post_delete' post.id %}" class="btn btn-primary">Delete</a>

            <h3>Comments</h3>
            
            <ul>
                {% for comment in post.comment_set.all %}
                    <li>
                        {{ comment.author }} :
                        {{ comment.message }}
                        at {{ comment.updated_at }}
                    </li>
                {% endfor %}
            </ul>

            <p>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="float-right">
            </form>
            </p>

            <hr/>
            <a href="{% url 'blog:post_list' %}" class="btn btn-primary"> To list </a>
            <a href="{% url 'blog:post_edit' post.id %}" class="btn btn-default">Modify</a>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/layout.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <table>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>{{ form.as_table }}</table>
                    <input type="submit" value="Post" class="btn btn-primary">
                </form>
            </table>

            <p>
                <a href="{% url 'blog:post_list' %}" class="btn btn-primary">Back to List</a>
            </p>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Start Django</h1>
        <p>I will be the winner</p>
        <p>
            <a class="btn btn-lg btn-primary" href="http://facebook.com/groups/askdjango">
                    Goto Home &raquo;
            </a>
        </p>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-info">
                <ul>
                    <li>http://localhost:8000/blog/ 으로 접속해 보세요</li>
                </ul>
            </div>

            <a href="{% url 'blog:post_new' %}" class="btn btn-primary float-right">New Post</a>

            <p>
                <form action="" method="GET">
                    <input type="text" name="q" value="{{ q }}">
                    <input class="btn btn-primary" type="submit" value="Search">
                </form>
            </p>
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>Title</td>
                        <td>Author</td>
                        <td>Last updated</td>
                    </tr>
                </thead>
            {% for post in post_list %}
                <tbody>
                    <tr>
                        <td>{{ post.id }}</td>
                        <td><a href="{% url 'blog:post_detail' post.id %}"> {{ post.title }} </a></td>
                        <td>{{ post.user }}</td>
                        <td>{{ post.updated_at }}</td>
                    </tr>
                </tbody>
            {% endfor %}
            </table>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/post_new.html
{% extends 'blog/layout.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <table>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>{{ form.as_table }}</table>
                    <input type="submit" value="Post" class="btn btn-primary">
                </form>
            </table>

            <p>
                <a href="{% url 'blog:post_list' %}" class="btn btn-primary">Back to List</a>
            </p>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/test_list.html
{% extends 'blog/layout.html' %}

{% block content %}

{% for post in post_list %}
<ul>
    <li>
        <ul>
            {{ post.title }}
            {% for comment in post.comment_set.all %}
            <li>
                {{ comment.message }}
            </li>
            {% endfor %}
        </ul>
    </li>
</ul>
{% endfor %}

{% endblock %}